In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/data.csv")
df

Country   Age Salary Purchased
0   France    44  72000        No
1    Spain    27  48000       Yes
2  Germany    30  54000        No
3    Spain    38  61000        No
4  Germany    40    NaN       Yes
5   France    35  58000       Yes
6    Spain   NaN  52000        No
7   France    48  79000       Yes
8  Germany    50  83000        No
9   France    37  67000       Yes

In [ ]:
x=df.loc[:,:'Salary'].values
x

array([['France', '44', '72000'],
       ['Spain', '27', '48000'],
       ['Germany', '30', '54000'],
       ['Spain', '38', '61000'],
       ['Germany', '40', ' NaN'],
       ['France', '35', '58000'],
       ['Spain', ' NaN', '52000'],
       ['France', '48', '79000'],
       ['Germany', '50', '83000'],
       ['France', '37', '67000']], dtype=object)

In [ ]:

df.iloc[:,:-1]


Country   Age Salary
0   France    44  72000
1    Spain    27  48000
2  Germany    30  54000
3    Spain    38  61000
4  Germany    40    NaN
5   France    35  58000
6    Spain   NaN  52000
7   France    48  79000
8  Germany    50  83000
9   France    37  67000

In [ ]:

y=df.iloc[:,3].values
df.iloc[:,3]

0      No
1     Yes
2      No
3      No
4     Yes
5     Yes
6      No
7     Yes
8      No
9     Yes
Name: Purchased, dtype: object

In [ ]:
df.head()

Country Age Salary Purchased
0   France  44  72000        No
1    Spain  27  48000       Yes
2  Germany  30  54000        No
3    Spain  38  61000        No
4  Germany  40    NaN       Yes

In [ ]:
df.tail()

Country   Age Salary Purchased
5   France    35  58000       Yes
6    Spain   NaN  52000        No
7   France    48  79000       Yes
8  Germany    50  83000        No
9   France    37  67000       Yes

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le_x=LabelEncoder()

In [ ]:
x[:,0]=le_x.fit_transform(x[:,0])

In [ ]:
x

array([[0, '44', '72000'],
       [2, '27', '48000'],
       [1, '30', '54000'],
       [2, '38', '61000'],
       [1, '40', ' NaN'],
       [0, '35', '58000'],
       [2, ' NaN', '52000'],
       [0, '48', '79000'],
       [1, '50', '83000'],
       [0, '37', '67000']], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder()
ohe.fit_transform(df.Country.values.reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
label_encode_y=LabelEncoder()
y=label_encode_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train


array([[1, '40', ' NaN'],
       [0, '37', '67000'],
       [2, '27', '48000'],
       [2, ' NaN', '52000'],
       [0, '48', '79000'],
       [2, '38', '61000'],
       [0, '44', '72000'],
       [0, '35', '58000']], dtype=object)

In [ ]:

y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [ ]:

x_test

array([[1, '30', '54000'],
       [1, '50', '83000']], dtype=object)

In [ ]:

y_test

array([0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler

sc_x=StandardScaler()

x_train_scale=sc_x.fit_transform(x_train)
x_test_scale=sc_x.fit_transform(x_test)
x_train_scale

array([[ 0.13483997,  0.25315802,         nan],
       [-0.94387981, -0.23014365,  0.44897083],
       [ 1.21355975, -1.84114924, -1.41706417],
       [ 1.21355975,         nan, -1.0242147 ],
       [-0.94387981,  1.54196248,  1.62751925],
       [ 1.21355975, -0.0690431 , -0.14030338],
       [-0.94387981,  0.89756025,  0.94003267],
       [-0.94387981, -0.55234477, -0.43494049]])

In [ ]:

x_test_scale

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])